# update-skills-list.ps1
# Scans .claude/commands and regenerates SKILLS.md

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptDir
$commandsDir = Join-Path $projectRoot ".claude\commands"
$outputFile = Join-Path $projectRoot "SKILLS.md"

$commandRows = [System.Collections.Generic.List[string]]::new()

if (Test-Path $commandsDir) {
    $commandFiles = Get-ChildItem -Path $commandsDir -Filter "*.md" | Sort-Object Name

    foreach ($file in $commandFiles) {
        $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
        $cmdName = $file.BaseName
        $name = ""
        $description = ""

        if ($content -match '(?s)^---.*?name:\s*(.+?)\s*\n') { $name = $matches[1].Trim() }
        if ($content -match '(?s)^---.*?description:\s*(.+?)\s*\n---') { $description = $matches[1].Trim() }

        if ($name -eq "") {
            if ($content -match '(?m)^#\s+(.+)$') { $name = $matches[1].Trim() }
        }
        if ($description -eq "") {
            $lines = ($content -split "`n") | Where-Object { $_.Trim() -ne "" -and -not $_.Trim().StartsWith("#") -and -not $_.Trim().StartsWith("---") }
            if ($lines.Count -gt 0) { $description = $lines[0].Trim() }
        }

        $relativePath = ".claude/commands/$($file.Name)"
        $commandRows.Add("| /$cmdName | [$name]($relativePath) | $description |")
    }
}

$fileContent = "# Slash Commands`n`n> This file is auto-generated by ``auto_script/update-skills-list.ps1``. Do not edit manually.`n`n"
$fileContent += "| Command | Name | Description |`n|---------|------|-------------|`n"
$fileContent += ($commandRows -join "`n") + "`n"

[System.IO.File]::WriteAllText($outputFile, $fileContent, [System.Text.Encoding]::UTF8)
Write-Host "SKILLS.md updated. Commands: $($commandRows.Count)"
